(declare-const freshvar$3 Int)
(declare-const count Int)
(declare-const curr Int)
(declare-const count Int)
(assert (= freshvar$3(+ count 1)))
(assert (not(>= count 0)))
(assert (= freshvar$3 count))
(assert (= curr count))
(assert (>= count 0))
(check-sat)
