pull_request_rules:
  - name: Auto merge when approves
    conditions:
      - "#approved-reviews-by>=1"
      - base=master
      - -conflict
      - "#changes-requested-reviews-by=0"
      - status-success=ci/circleci
    actions:
      merge:
        method: rebase
  - name: Auto merge when labelled fast merge
    conditions:
      - label=fast-merge
      - base=master
      - -conflict
      - "#changes-requested-reviews-by=0"
      - status-success=ci/circleci
    actions:
      merge:
        method: rebase
  - name: Delete head branch after merge
    conditions: []
    actions:
      delete_head_branch: {}
