name: Changelog

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Changelog Reminder
      uses: peterjgrainger/action-changelog-reminder@v1.1.0
      with:
        changelog_regex: '^CHANGES.md$'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
