name: Main workflow

on:
  - pull_request
  - push

jobs:
  build:
    strategy:
      matrix:
        ocaml-version:
          - 4.12.x
          - 4.13.x

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use OCaml ${{ matrix.ocaml-version }}
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-version }}

      - name: Cache opam
        uses: actions/cache@v2
        with:
          path: _opam
          key: ${{ runner.os }}-${{ matrix.ocaml-version }}-${{ hashFiles('dune-project') }}

      - run: opam install . --deps-only --with-doc --with-test

      - run: opam exec -- dune build

      - run: opam exec -- dune runtest

      - run: opam install ocamlformat=0.19.0

      - run: opam exec -- dune build @fmt
