name: Main workflow

on:
  - pull_request
  - push

jobs:
  build:
    strategy:
      matrix:
        ocaml-version:
          - "5.1"
          - "4.14"

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Use OCaml ${{ matrix.ocaml-version }}
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ${{ matrix.ocaml-version }}
          cache-prefix: v3

      - run: opam install . --deps-only --with-doc --with-test

      - run: opam exec -- dune build

      - run: opam exec -- dune runtest

      - run: opam install ocamlformat=0.27.0

      - run: opam exec -- dune build @fmt
