name: Main workflow

on:
  - pull_request
  - push

jobs:
  build:
    strategy:
      matrix:
        ocaml-version:
          - 5.4
          - 5.3

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use OCaml ${{ matrix.ocaml-version }}
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ${{ matrix.ocaml-version }}
          opam-local-packages: '*.opam'
          dune-cache: true
          cache-prefix: v3

      - run: opam install . --deps-only --with-doc --with-test

      - run: opam exec -- dune build

      - run: opam exec -- dune runtest

      - run: opam install ocamlformat=0.29.0

      - run: opam exec -- dune build @fmt
